baseURL = "https://example.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Docs APi Brawl Stars"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
